// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService Agent 管理与权限配置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../../permission/models.js";

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function List() {
    return $Call.ByID(188410106).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetPermission 更新某 Agent 的权限策略。
 * @param {string} id
 * @param {permission$0.Policy} policy
 * @returns {$CancellablePromise<void>}
 */
export function SetPermission(id, policy) {
    return $Call.ByID(2592589049, id, policy);
}

/**
 * Test 用空任务测试 Agent 可用性(仅检查注册与配置)。
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Test(id) {
    return $Call.ByID(3353976630, id);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
