// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService Agent 管理与权限配置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../../permission/models.js";

/**
 * GetConfig 返回某 Agent 的运行配置(环境变量值已掩码为 ***)。
 */
export function GetConfig(id: string): $CancellablePromise<agent$0.AgentConfig> {
    return $Call.ByID(931224948, id);
}

export function List(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(188410106);
}

/**
 * SetPermission 更新某 Agent 的权限策略。
 */
export function SetPermission(id: string, policy: permission$0.Policy): $CancellablePromise<void> {
    return $Call.ByID(2592589049, id, policy);
}

/**
 * Test 用空任务测试 Agent 可用性(仅检查注册与配置)。
 */
export function Test(id: string): $CancellablePromise<string> {
    return $Call.ByID(3353976630, id);
}

/**
 * UpdateConfig 保存某 Agent 的运行配置并热重建适配器实例。
 * 隔离原则:配置只影响本应用对该 Agent 的调用(CLI 参数 + 子进程环境变量),
 * 不会修改用户的本地配置文件;环境变量值为 "***" 表示保留原值,空串表示删除。
 */
export function UpdateConfig(id: string, cfg: agent$0.AgentConfig): $CancellablePromise<void> {
    return $Call.ByID(1994183317, id, cfg);
}
