// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecutionService 执行管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as persistence$0 from "../../persistence/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../workflow/model/models.js";

/**
 * AllEvents 跨执行审计事件流。
 */
export function AllEvents(eventType: string, limit: number): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3591774373, eventType, limit);
}

export function Artifacts(id: string): $CancellablePromise<(model$0.Artifact | null)[] | null> {
    return $Call.ByID(1145309656, id);
}

export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2074839491, id);
}

export function Events(id: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3974311676, id);
}

/**
 * Export 汇出执行完整记录(执行+节点+事件+制品),用于审计归档。
 */
export function Export(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1601888123, id);
}

export function Get(id: string): $CancellablePromise<model$0.Execution | null> {
    return $Call.ByID(3504044623, id);
}

export function List(workflowID: string, limit: number): $CancellablePromise<(model$0.Execution | null)[] | null> {
    return $Call.ByID(4221995049, workflowID, limit);
}

export function Nodes(id: string): $CancellablePromise<(model$0.ExecutionNode | null)[] | null> {
    return $Call.ByID(2835310866, id);
}

/**
 * ProvideInput 人工输入后恢复执行(同样使用脱离请求的 context)。
 */
export function ProvideInput(id: string, response: { [_ in string]?: any } | null): $CancellablePromise<model$0.Execution | null> {
    return $Call.ByID(3860795042, id, response);
}

/**
 * RetryNode 重试失败节点或跳过继续(skip=true)。
 */
export function RetryNode(id: string, skip: boolean): $CancellablePromise<model$0.Execution | null> {
    return $Call.ByID(3308931305, id, skip);
}

/**
 * Run 启动执行(异步,立即返回 Execution 记录)。
 * 使用脱离请求的生命周期 context:HTTP 响应返回后执行继续在后台进行。
 */
export function Run(workflowID: string, task: string, variables: { [_ in string]?: any } | null): $CancellablePromise<model$0.Execution | null> {
    return $Call.ByID(3075246354, workflowID, task, variables);
}

/**
 * Stats 返回每工作流执行统计。
 */
export function Stats(): $CancellablePromise<persistence$0.WorkflowStats[] | null> {
    return $Call.ByID(4280310500);
}
