// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecutionService 执行管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../workflow/model/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<(model$0.Artifact | null)[]>}
 */
export function Artifacts(id) {
    return $Call.ByID(1145309656, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(id) {
    return $Call.ByID(2074839491, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function Events(id) {
    return $Call.ByID(3974311676, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<model$0.Execution | null>}
 */
export function Get(id) {
    return $Call.ByID(3504044623, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} workflowID
 * @param {number} limit
 * @returns {$CancellablePromise<(model$0.Execution | null)[]>}
 */
export function List(workflowID, limit) {
    return $Call.ByID(4221995049, workflowID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<(model$0.ExecutionNode | null)[]>}
 */
export function Nodes(id) {
    return $Call.ByID(2835310866, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ProvideInput 人工输入后恢复执行(同样使用脱离请求的 context)。
 * @param {string} id
 * @param {{ [_ in string]?: any }} response
 * @returns {$CancellablePromise<model$0.Execution | null>}
 */
export function ProvideInput(id, response) {
    return $Call.ByID(3860795042, id, response).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * RetryNode 重试失败节点或跳过继续(skip=true)。
 * @param {string} id
 * @param {boolean} skip
 * @returns {$CancellablePromise<model$0.Execution | null>}
 */
export function RetryNode(id, skip) {
    return $Call.ByID(3308931305, id, skip).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * Run 启动执行(异步,立即返回 Execution 记录)。
 * 使用脱离请求的生命周期 context:HTTP 响应返回后执行继续在后台进行。
 * @param {string} workflowID
 * @param {string} task
 * @param {{ [_ in string]?: any }} variables
 * @returns {$CancellablePromise<model$0.Execution | null>}
 */
export function Run(workflowID, task, variables) {
    return $Call.ByID(3075246354, workflowID, task, variables).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.Artifact.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.Execution.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.ExecutionNode.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
