// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService Git API。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../git/models.js";

/**
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function Commit(message) {
    return $Call.ByID(688539026, message);
}

/**
 * @param {boolean} staged
 * @returns {$CancellablePromise<string>}
 */
export function Diff(staged) {
    return $Call.ByID(1443102504, staged);
}

/**
 * @param {number} maxCount
 * @returns {$CancellablePromise<git$0.LogEntry[]>}
 */
export function Log(maxCount) {
    return $Call.ByID(2199767627, maxCount).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetWorkingDir 更新 Git 工作目录。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkingDir(dir) {
    return $Call.ByID(1240058987, dir);
}

/**
 * @returns {$CancellablePromise<git$0.Status | null>}
 */
export function Status() {
    return $Call.ByID(3995149421).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = git$0.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = git$0.Status.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
