// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService Git API。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../../git/models.js";

export function Commit(message: string): $CancellablePromise<string> {
    return $Call.ByID(688539026, message);
}

export function Diff(staged: boolean): $CancellablePromise<string> {
    return $Call.ByID(1443102504, staged);
}

export function Log(maxCount: number): $CancellablePromise<git$0.LogEntry[] | null> {
    return $Call.ByID(2199767627, maxCount);
}

/**
 * SetWorkingDir 更新 Git 工作目录。
 */
export function SetWorkingDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1240058987, dir);
}

export function Status(): $CancellablePromise<git$0.Status | null> {
    return $Call.ByID(3995149421);
}
