// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsInfo 是设置页展示的只读信息 + 可修改项。
 */
export interface SettingsInfo {
    "data_dir": string;
    "git_working_dir": string;
    "log_level": string;
}
