// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SettingsInfo 是设置页展示的只读信息 + 可修改项。
 */
export class SettingsInfo {
    /**
     * Creates a new SettingsInfo instance.
     * @param {Partial<SettingsInfo>} [$$source = {}] - The source object to create the SettingsInfo.
     */
    constructor($$source = {}) {
        if (!("data_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data_dir"] = "";
        }
        if (!("git_working_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["git_working_dir"] = "";
        }
        if (!("log_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInfo(/** @type {Partial<SettingsInfo>} */($$parsedSource));
    }
}
