// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} key
 * @param {any} out
 * @returns {$CancellablePromise<void>}
 */
export function Get(key, out) {
    return $Call.ByID(2745401046, key, out);
}

/**
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<void>}
 */
export function Set(key, value) {
    return $Call.ByID(833733018, key, value);
}
