// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(key: string, out: any): $CancellablePromise<void> {
    return $Call.ByID(2745401046, key, out);
}

/**
 * Info 返回当前设置。
 */
export function Info(): $CancellablePromise<$models.SettingsInfo | null> {
    return $Call.ByID(3803811458);
}

export function Set(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(833733018, key, value);
}

/**
 * Update 更新设置:git_working_dir / log_level(日志级别即时生效)。
 */
export function Update(gitWorkingDir: string, logLevel: string): $CancellablePromise<$models.SettingsInfo | null> {
    return $Call.ByID(1778497747, gitWorkingDir, logLevel);
}
