// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Update 更新设置:git_working_dir / log_level(日志级别即时生效)。
 * ExportBackup 导出全部工作流与 Agent 配置(备份用;含明文敏感环境变量,请妥善保管)。
 */
export function ExportBackup(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(972086262);
}

export function Get(key: string, out: any): $CancellablePromise<void> {
    return $Call.ByID(2745401046, key, out);
}

/**
 * Info 返回当前设置。
 */
export function Info(): $CancellablePromise<$models.SettingsInfo | null> {
    return $Call.ByID(3803811458);
}

/**
 * RestoreBackup 恢复备份:已存在同 ID 工作流跳过(避免覆盖用户修改),
 * Agent 配置覆盖写入。
 * 输入统一经 JSON 归一:API/前端路径是 []any + map[string]any,
 * 进程内路径(ExportBackup 直出)是 []model.Workflow + map[string]json.RawMessage。
 */
export function RestoreBackup(backup: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(283548462, backup);
}

export function Set(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(833733018, key, value);
}

export function Update(gitWorkingDir: string, logLevel: string): $CancellablePromise<$models.SettingsInfo | null> {
    return $Call.ByID(1778497747, gitWorkingDir, logLevel);
}
