// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService Skill 管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../../skill/models.js";

export function List(): $CancellablePromise<skill$0.DTO[] | null> {
    return $Call.ByID(3368373862);
}

/**
 * Test 执行一次 Skill 测试调用。
 */
export function Test(id: string): $CancellablePromise<string> {
    return $Call.ByID(636958378, id);
}
