// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService Skill 管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../../skill/models.js";

/**
 * @returns {$CancellablePromise<skill$0.DTO[]>}
 */
export function List() {
    return $Call.ByID(3368373862).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetEnabled 启用/禁用 Skill(禁用后运行时拒绝调用)。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(id, enabled) {
    return $Call.ByID(1620570695, id, enabled);
}

/**
 * Test 执行一次 Skill 测试调用。
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Test(id) {
    return $Call.ByID(636958378, id);
}

// Private type creation functions
const $$createType0 = skill$0.DTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
