// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkflowService 工作流 CRUD/校验/导出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../workflow/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as validator$0 from "../../workflow/validator/models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2490950045, id);
}

/**
 * Duplicate 复制工作流。
 */
export function Duplicate(id: string): $CancellablePromise<model$0.Workflow | null> {
    return $Call.ByID(627075187, id);
}

/**
 * ExportYAML 导出 DSL。
 */
export function ExportYAML(id: string): $CancellablePromise<string> {
    return $Call.ByID(3454351311, id);
}

export function Get(id: string): $CancellablePromise<model$0.Workflow | null> {
    return $Call.ByID(453769934, id);
}

/**
 * ImportYAML 导入 DSL 文本创建工作流。
 * ID 冲突时自动分配新 ID;导入前必须通过校验。
 */
export function ImportYAML(content: string): $CancellablePromise<model$0.Workflow | null> {
    return $Call.ByID(1216022400, content);
}

export function List(): $CancellablePromise<(model$0.Workflow | null)[] | null> {
    return $Call.ByID(1924388702);
}

/**
 * Save 创建或更新(传入带 ID 的 workflow;存在则版本+1)。
 */
export function Save(wf: model$0.Workflow | null): $CancellablePromise<model$0.Workflow | null> {
    return $Call.ByID(3116476783, wf);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<model$0.Workflow | null> {
    return $Call.ByID(3280761087, id, enabled);
}

/**
 * Validate 返回结构化校验结果。
 */
export function Validate(wf: model$0.Workflow | null): $CancellablePromise<validator$0.Result | null> {
    return $Call.ByID(1569125308, wf);
}

/**
 * VersionDSL 返回指定版本的 DSL 文本(从版本快照导出)。
 */
export function VersionDSL(id: string, version: number): $CancellablePromise<string> {
    return $Call.ByID(1047249505, id, version);
}

export function Versions(id: string): $CancellablePromise<number[] | null> {
    return $Call.ByID(2322618727, id);
}
