// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkflowService 工作流 CRUD/校验/导出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../workflow/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as validator$0 from "../../workflow/validator/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2490950045, id);
}

/**
 * Duplicate 复制工作流。
 * @param {string} id
 * @returns {$CancellablePromise<model$0.Workflow | null>}
 */
export function Duplicate(id) {
    return $Call.ByID(627075187, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportYAML 导出 DSL。
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ExportYAML(id) {
    return $Call.ByID(3454351311, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<model$0.Workflow | null>}
 */
export function Get(id) {
    return $Call.ByID(453769934, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportYAML 导入 DSL 文本创建工作流。
 * ID 冲突时自动分配新 ID;导入前必须通过校验。
 * @param {string} content
 * @returns {$CancellablePromise<model$0.Workflow | null>}
 */
export function ImportYAML(content) {
    return $Call.ByID(1216022400, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<(model$0.Workflow | null)[]>}
 */
export function List() {
    return $Call.ByID(1924388702).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Save 创建或更新(传入带 ID 的 workflow;存在则版本+1)。
 * @param {model$0.Workflow | null} wf
 * @returns {$CancellablePromise<model$0.Workflow | null>}
 */
export function Save(wf) {
    return $Call.ByID(3116476783, wf).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<model$0.Workflow | null>}
 */
export function SetEnabled(id, enabled) {
    return $Call.ByID(3280761087, id, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Validate 返回结构化校验结果。
 * @param {model$0.Workflow | null} wf
 * @returns {$CancellablePromise<validator$0.Result | null>}
 */
export function Validate(wf) {
    return $Call.ByID(1569125308, wf).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * VersionDSL 返回指定版本的 DSL 文本(从版本快照导出)。
 * @param {string} id
 * @param {number} version
 * @returns {$CancellablePromise<string>}
 */
export function VersionDSL(id, version) {
    return $Call.ByID(1047249505, id, version);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<number[]>}
 */
export function Versions(id) {
    return $Call.ByID(2322618727, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.Workflow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = validator$0.Result.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
