// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WorkflowStats 是某工作流的执行统计。
 */
export class WorkflowStats {
    /**
     * Creates a new WorkflowStats instance.
     * @param {Partial<WorkflowStats>} [$$source = {}] - The source object to create the WorkflowStats.
     */
    constructor($$source = {}) {
        if (!("workflow_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("waiting" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waiting"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["running"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkflowStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowStats(/** @type {Partial<WorkflowStats>} */($$parsedSource));
    }
}
