// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkflowStats 是某工作流的执行统计。
 */
export interface WorkflowStats {
    "workflow_id": string;
    "name": string;
    "total": number;
    "completed": number;
    "failed": number;
    "waiting": number;
    "running": number;
}
