// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Policy 是单个 Agent 的权限集合。未显式授权的动作一律拒绝。
 */
export interface Policy {
    /**
     * FilesystemRead / FilesystemWrite 控制对工作目录的读写。
     */
    "filesystem_read": boolean;
    "filesystem_write": boolean;

    /**
     * GitRead / GitCommit / GitPush 控制 Git 能力。
     */
    "git_read": boolean;
    "git_commit": boolean;
    "git_push": boolean;
}
