// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Policy 是单个 Agent 的权限集合。未显式授权的动作一律拒绝。
 */
export class Policy {
    /**
     * Creates a new Policy instance.
     * @param {Partial<Policy>} [$$source = {}] - The source object to create the Policy.
     */
    constructor($$source = {}) {
        if (!("filesystem_read" in $$source)) {
            /**
             * FilesystemRead / FilesystemWrite 控制对工作目录的读写。
             * @member
             * @type {boolean}
             */
            this["filesystem_read"] = false;
        }
        if (!("filesystem_write" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["filesystem_write"] = false;
        }
        if (!("git_read" in $$source)) {
            /**
             * GitRead / GitCommit / GitPush 控制 Git 能力。
             * @member
             * @type {boolean}
             */
            this["git_read"] = false;
        }
        if (!("git_commit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["git_commit"] = false;
        }
        if (!("git_push" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["git_push"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Policy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Policy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Policy(/** @type {Partial<Policy>} */($$parsedSource));
    }
}
