// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DTO 是给前端的 Skill 描述。
 */
export interface DTO {
    "id": string;
    "name": string;
    "description": string;
    "enabled": boolean;
}
