// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Result 是一次校验的结果。
 */
export interface Result {
    "valid": boolean;
    "errors": ValidationError[] | null;
    "warnings": ValidationError[] | null;
}

/**
 * ValidationError 是单条校验错误。
 */
export interface ValidationError {
    "code": string;
    "node"?: string;
    "edge"?: string;
    "message": string;
}
