// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Artifact 是执行过程中产生的制品(例如 plan、diff、review 结果)。
 */
export interface Artifact {
    "id": string;
    "execution_id": string;
    "node_id": string;
    "name": string;
    "content_type": string;
    "content": string;
    "created_at": string;
}

/**
 * Edge 连接两个节点。Condition 为空表示无条件跳转。
 */
export interface Edge {
    "from": string;
    "to": string;
    "condition"?: string;
}

/**
 * Execution 是一次 Workflow 运行实例。它绑定具体的 Workflow 版本,
 * 保证运行中的 Execution 不受后续修改影响。
 */
export interface Execution {
    "id": string;
    "workflow_id": string;
    "workflow_version": number;
    "workflow_name": string;
    "state": ExecutionState;
    "task": string;
    "variables"?: { [_ in string]?: any } | null;
    "current_node_id"?: string;
    "iterations"?: { [_ in string]?: number } | null;
    "created_at": string;
    "started_at"?: string;
    "finished_at"?: string;
    "error"?: string;
    "node_states"?: { [_ in string]?: string } | null;

    /**
     * StateData 是运行时的会话状态快照(用于恢复与 UI 查询)。
     */
    "state_data"?: { [_ in string]?: any } | null;
}

/**
 * ExecutionNode 记录某个节点在某次 Execution 中的执行明细。
 */
export interface ExecutionNode {
    "id": string;
    "execution_id": string;
    "node_id": string;
    "node_type": NodeType;
    "node_name": string;
    "state": NodeState;
    "attempt": number;
    "output"?: string;
    "result_json"?: string;
    "error"?: string;
    "started_at"?: string;
    "finished_at"?: string;
    "duration_ms"?: number;
}

/**
 * ExecutionState 是 Execution 的状态机状态。
 */
export enum ExecutionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExecutionCreated = "CREATED",
    ExecutionRunning = "RUNNING",
    ExecutionPaused = "PAUSED",
    ExecutionWaitingUser = "WAITING_USER",
    ExecutionCompleted = "COMPLETED",
    ExecutionFailed = "FAILED",
    ExecutionCancelled = "CANCELLED",
};

/**
 * Node 是 Workflow 图中的一个节点。
 */
export interface Node {
    "id": string;
    "name": string;
    "type": NodeType;
    "config"?: { [_ in string]?: any } | null;
    "position": Position;
}

/**
 * NodeState 是单个 Node 执行的状态。
 */
export enum NodeState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodePending = "PENDING",
    NodeRunning = "RUNNING",
    NodeSuccess = "SUCCESS",
    NodeFailed = "FAILED",
    NodeSkipped = "SKIPPED",
    NodeWaiting = "WAITING",
};

/**
 * NodeType 标识 Node 的类型。类型是可注册扩展的,不写死在 UI 或 Engine 中。
 */
export enum NodeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeTypeAgent = "agent",
    NodeTypeSkill = "skill",
    NodeTypeCondition = "condition",
    NodeTypeParallel = "parallel",
    NodeTypeMerge = "merge",
    NodeTypeHuman = "human",
    NodeTypeScript = "script",
    NodeTypeGit = "git",
    NodeTypeSubWorkflow = "subworkflow",
};

/**
 * Position 是节点在画布上的坐标。
 */
export interface Position {
    "x": number;
    "y": number;
}

/**
 * Workflow 是用户可配置的编排定义。
 */
export interface Workflow {
    "id": string;
    "name": string;
    "description": string;
    "version": number;
    "enabled": boolean;
    "variables"?: { [_ in string]?: any } | null;

    /**
     * Permission 工作流级权限覆盖(需求:DSL permissions 段)。
     */
    "permission"?: { [_ in string]?: any } | null;
    "nodes": Node[] | null;
    "edges": Edge[] | null;
    "settings": WorkflowSettings;
    "created_at"?: string;
    "updated_at"?: string;
}

/**
 * WorkflowSettings 控制 Workflow 级别的执行策略。
 */
export interface WorkflowSettings {
    /**
     * MaxIterations 限制循环(如 Review→Fix)的最大轮数,防止无限循环。
     */
    "max_iterations"?: number;

    /**
     * OnLoopLimit 达到循环上限后的处理策略:wait_user(默认)或 fail。
     */
    "on_loop_limit"?: string;

    /**
     * TimeoutSeconds 单轮执行超时(秒);0 = 不限。
     */
    "timeout_seconds"?: number;
}
