// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Artifact 是执行过程中产生的制品(例如 plan、diff、review 结果)。
 */
export class Artifact {
    /**
     * Creates a new Artifact instance.
     * @param {Partial<Artifact>} [$$source = {}] - The source object to create the Artifact.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("execution_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["execution_id"] = "";
        }
        if (!("node_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["node_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content_type"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Artifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artifact(/** @type {Partial<Artifact>} */($$parsedSource));
    }
}

/**
 * Edge 连接两个节点。Condition 为空表示无条件跳转。
 */
export class Edge {
    /**
     * Creates a new Edge instance.
     * @param {Partial<Edge>} [$$source = {}] - The source object to create the Edge.
     */
    constructor($$source = {}) {
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["condition"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Edge instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Edge}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Edge(/** @type {Partial<Edge>} */($$parsedSource));
    }
}

/**
 * Execution 是一次 Workflow 运行实例。它绑定具体的 Workflow 版本,
 * 保证运行中的 Execution 不受后续修改影响。
 */
export class Execution {
    /**
     * Creates a new Execution instance.
     * @param {Partial<Execution>} [$$source = {}] - The source object to create the Execution.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("workflow_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow_id"] = "";
        }
        if (!("workflow_version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workflow_version"] = 0;
        }
        if (!("workflow_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow_name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {ExecutionState}
             */
            this["state"] = ExecutionState.$zero;
        }
        if (!("task" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["task"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["variables"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["current_node_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["iterations"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["finished_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["node_states"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * StateData 是运行时的会话状态快照(用于恢复与 UI 查询)。
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["state_data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Execution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Execution}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField13_0 = $$createType2;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField6_0($$parsedSource["variables"]);
        }
        if ("iterations" in $$parsedSource) {
            $$parsedSource["iterations"] = $$createField8_0($$parsedSource["iterations"]);
        }
        if ("node_states" in $$parsedSource) {
            $$parsedSource["node_states"] = $$createField13_0($$parsedSource["node_states"]);
        }
        if ("state_data" in $$parsedSource) {
            $$parsedSource["state_data"] = $$createField14_0($$parsedSource["state_data"]);
        }
        return new Execution(/** @type {Partial<Execution>} */($$parsedSource));
    }
}

/**
 * ExecutionNode 记录某个节点在某次 Execution 中的执行明细。
 */
export class ExecutionNode {
    /**
     * Creates a new ExecutionNode instance.
     * @param {Partial<ExecutionNode>} [$$source = {}] - The source object to create the ExecutionNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("execution_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["execution_id"] = "";
        }
        if (!("node_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["node_id"] = "";
        }
        if (!("node_type" in $$source)) {
            /**
             * @member
             * @type {NodeType}
             */
            this["node_type"] = NodeType.$zero;
        }
        if (!("node_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["node_name"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {NodeState}
             */
            this["state"] = NodeState.$zero;
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result_json"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["finished_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["duration_ms"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecutionNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionNode(/** @type {Partial<ExecutionNode>} */($$parsedSource));
    }
}

/**
 * ExecutionState 是 Execution 的状态机状态。
 * @readonly
 * @enum {string}
 */
export const ExecutionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ExecutionCreated: "CREATED",
    ExecutionRunning: "RUNNING",
    ExecutionPaused: "PAUSED",
    ExecutionWaitingUser: "WAITING_USER",
    ExecutionCompleted: "COMPLETED",
    ExecutionFailed: "FAILED",
    ExecutionCancelled: "CANCELLED",
};

/**
 * Node 是 Workflow 图中的一个节点。
 */
export class Node {
    /**
     * Creates a new Node instance.
     * @param {Partial<Node>} [$$source = {}] - The source object to create the Node.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {NodeType}
             */
            this["type"] = NodeType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["config"] = undefined;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {Position}
             */
            this["position"] = (new Position());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Node}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField3_0($$parsedSource["config"]);
        }
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField4_0($$parsedSource["position"]);
        }
        return new Node(/** @type {Partial<Node>} */($$parsedSource));
    }
}

/**
 * NodeState 是单个 Node 执行的状态。
 * @readonly
 * @enum {string}
 */
export const NodeState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    NodePending: "PENDING",
    NodeRunning: "RUNNING",
    NodeSuccess: "SUCCESS",
    NodeFailed: "FAILED",
    NodeSkipped: "SKIPPED",
    NodeWaiting: "WAITING",
};

/**
 * NodeType 标识 Node 的类型。类型是可注册扩展的,不写死在 UI 或 Engine 中。
 * @readonly
 * @enum {string}
 */
export const NodeType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    NodeTypeAgent: "agent",
    NodeTypeSkill: "skill",
    NodeTypeCondition: "condition",
    NodeTypeParallel: "parallel",
    NodeTypeMerge: "merge",
    NodeTypeHuman: "human",
    NodeTypeScript: "script",
    NodeTypeGit: "git",
    NodeTypeSubWorkflow: "subworkflow",
};

/**
 * Position 是节点在画布上的坐标。
 */
export class Position {
    /**
     * Creates a new Position instance.
     * @param {Partial<Position>} [$$source = {}] - The source object to create the Position.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Position}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position(/** @type {Partial<Position>} */($$parsedSource));
    }
}

/**
 * Workflow 是用户可配置的编排定义。
 */
export class Workflow {
    /**
     * Creates a new Workflow instance.
     * @param {Partial<Workflow>} [$$source = {}] - The source object to create the Workflow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["variables"] = undefined;
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {Node[]}
             */
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            /**
             * @member
             * @type {Edge[]}
             */
            this["edges"] = [];
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {WorkflowSettings}
             */
            this["settings"] = (new WorkflowSettings());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["created_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updated_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workflow}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField5_0($$parsedSource["variables"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField6_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField7_0($$parsedSource["edges"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField8_0($$parsedSource["settings"]);
        }
        return new Workflow(/** @type {Partial<Workflow>} */($$parsedSource));
    }
}

/**
 * WorkflowSettings 控制 Workflow 级别的执行策略。
 */
export class WorkflowSettings {
    /**
     * Creates a new WorkflowSettings instance.
     * @param {Partial<WorkflowSettings>} [$$source = {}] - The source object to create the WorkflowSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * MaxIterations 限制循环(如 Review→Fix)的最大轮数,防止无限循环。
             * @member
             * @type {number | undefined}
             */
            this["max_iterations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * OnLoopLimit 达到循环上限后的处理策略:wait_user(默认)或 fail。
             * @member
             * @type {string | undefined}
             */
            this["on_loop_limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkflowSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowSettings(/** @type {Partial<WorkflowSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = Position.createFrom;
const $$createType4 = Node.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Edge.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = WorkflowSettings.createFrom;
