// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogEntry 是一条提交记录。
 */
export interface LogEntry {
    "hash": string;
    "author": string;
    "date": string;
    "subject": string;
}

/**
 * Status 表示 git status 的结构化结果。
 */
export interface Status {
    "branch": string;
    "modified": string[] | null;
    "staged": string[] | null;
    "untracked": string[] | null;
    "short": string;
}
