// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentConfig 是每个 Agent 的运行配置:模型、端点、超时与调用级环境变量。
 * 
 * 隔离原则:这些配置只影响本应用对该 Agent 的调用方式
 * (CLI 参数 + 子进程环境变量),绝不读写用户的本地配置文件
 * (~/.claude、~/.pi 等),也不写入工作流 DSL。
 */
export interface AgentConfig {
    /**
     * Model 默认模型(如 claude-sonnet-4-5),节点可通过 config.model 覆盖。
     */
    "model": string;

    /**
     * BaseURL API 端点(可选)。claude-code 映射为 ANTHROPIC_BASE_URL,
     * pi-agent 映射为 PI_BASE_URL;留空使用各自的默认端点。
     */
    "base_url": string;

    /**
     * TimeoutSeconds 默认超时;0 表示使用适配器内置默认值。
     */
    "timeout_seconds": number;

    /**
     * ExtraArgs 追加 CLI 参数。
     */
    "extra_args": string[] | null;

    /**
     * Env 调用级环境变量覆盖(如 ANTHROPIC_AUTH_TOKEN)。值属于敏感信息,
     * 通过 API 返回时会被掩码;持久化于本地 SQLite,不进入日志与工作流。
     */
    "env": { [_ in string]?: string } | null;

    /**
     * DefaultWorkingDir 默认工作目录(节点未指定时使用)。
     */
    "default_working_dir": string;

    /**
     * Behavior 仅用于 Mock Agent 的演示脚本:
     * {"review": {"decisions": ["REJECTED","APPROVED"], "summary_template": "..."}}
     */
    "behavior"?: { [_ in string]?: any } | null;
}
