// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentConfig 是每个 Agent 的运行配置:模型、端点、超时与调用级环境变量。
 * 
 * 隔离原则:这些配置只影响本应用对该 Agent 的调用方式
 * (CLI 参数 + 子进程环境变量),绝不读写用户的本地配置文件
 * (~/.claude、~/.pi 等),也不写入工作流 DSL。
 */
export class AgentConfig {
    /**
     * Creates a new AgentConfig instance.
     * @param {Partial<AgentConfig>} [$$source = {}] - The source object to create the AgentConfig.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * Model 默认模型(如 claude-sonnet-4-5),节点可通过 config.model 覆盖。
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("base_url" in $$source)) {
            /**
             * BaseURL API 端点(可选)。claude-code 映射为 ANTHROPIC_BASE_URL,
             * pi-agent 映射为 PI_BASE_URL;留空使用各自的默认端点。
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("timeout_seconds" in $$source)) {
            /**
             * TimeoutSeconds 默认超时;0 表示使用适配器内置默认值。
             * @member
             * @type {number}
             */
            this["timeout_seconds"] = 0;
        }
        if (!("extra_args" in $$source)) {
            /**
             * ExtraArgs 追加 CLI 参数。
             * @member
             * @type {string[]}
             */
            this["extra_args"] = [];
        }
        if (!("env" in $$source)) {
            /**
             * Env 调用级环境变量覆盖(如 ANTHROPIC_AUTH_TOKEN)。值属于敏感信息,
             * 通过 API 返回时会被掩码;持久化于本地 SQLite,不进入日志与工作流。
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["env"] = {};
        }
        if (!("default_working_dir" in $$source)) {
            /**
             * DefaultWorkingDir 默认工作目录(节点未指定时使用)。
             * @member
             * @type {string}
             */
            this["default_working_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra_args" in $$parsedSource) {
            $$parsedSource["extra_args"] = $$createField3_0($$parsedSource["extra_args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        return new AgentConfig(/** @type {Partial<AgentConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
